# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jp-nbdev-test',
                'doc_host': 'https://j-parkes-nel.github.io',
                'git_url': 'https://github.com/j-parkes-nel/jp-nbdev-test',
                'lib_path': 'jp_nbdev_test'},
  'syms': {'jp_nbdev_test.core': {'jp_nbdev_test.core.foo': ('core.html#foo', 'jp_nbdev_test/core.py')}}}
